# Generated by Django 5.2.6 on 2025-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiales/')),
                ('tipo', models.CharField(choices=[('critico', 'Material Crítico'), ('interno', 'Material Interno')], default='interno', max_length=10)),
            ],
        ),
    ]
